#!/usr/bin/env python3
"""Repair Gemini-generated auto-grading workbooks.

By default this script performs discovery and verification only. Pass --apply to
write the workbook changes.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from openpyxl import load_workbook


ROOT = Path(__file__).resolve().parents[1]
GENERATOR_LABEL = "Gemini 3.1 Pro"
GENERATED_BY_LABEL = f"Generated by {GENERATOR_LABEL}"
GRADING_SHEET_CANDIDATES = (
    "Gemini Generation",
    "Gemini 3.1 Pro Generation",
    "Gemini 3.1 Pro Grading",
    "GPT-5.5 Grading",
)
STALE_FORMULA_REFS = (
    "'GPT-5 Generation'!",
    "'Gemini Generation'!",
    "'Gemini 3.1 Pro Generation'!",
)
METRICS_SHEET = "Metrics"
HEADER = ["Type", "Element", "Grading", "Notes"]
VALID_GRADES = {"0", "0.5", "1"}


@dataclass(frozen=True)
class WorkbookSet:
    name: str
    workbook_glob: str
    tsv_name: str
    grading_sheet: str
    grader_label: str


WORKBOOK_SETS = (
    WorkbookSet(
        name="Gemini generation / Gemini grading",
        workbook_glob=(
            "*/Grading/2 stage/6-examples/"
            "*Gemini3.1ProPreviewGeneration_Gemini3.1ProPreviewAutoGrading.xlsx"
        ),
        tsv_name=(
            "grading_results__generated-by-gemini-3.1-pro-preview__"
            "graded-by-gemini-3.1-pro-preview.tsv"
        ),
        grading_sheet="Gemini 3.1 Pro Grading",
        grader_label="Gemini 3.1 Pro",
    ),
    WorkbookSet(
        name="Gemini generation / GPT-5.5 grading",
        workbook_glob=(
            "*/Grading/2 stage/6-examples/"
            "*Gemini3.1ProPreviewGeneration_GPT5.5AutoGrading.xlsx"
        ),
        tsv_name=(
            "grading_results__generated-by-gemini-3.1-pro-preview__"
            "graded-by-GPT-5.5.tsv"
        ),
        grading_sheet="GPT-5.5 Grading",
        grader_label="GPT-5.5",
    ),
)


@dataclass(frozen=True)
class WorkbookPair:
    workbook_set: WorkbookSet
    model: str
    workbook: Path
    tsv: Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Paste Gemini-generated grading TSVs into matching xlsx files."
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Write workbook changes. Without this flag, only preflight is run.",
    )
    return parser.parse_args()


def discover_pairs() -> list[WorkbookPair]:
    pairs: list[WorkbookPair] = []
    for workbook_set in WORKBOOK_SETS:
        for workbook in sorted(ROOT.glob(workbook_set.workbook_glob)):
            if workbook.name.startswith("~$"):
                continue
            model = workbook.relative_to(ROOT).parts[0]
            tsv = ROOT / "gemini-generated" / model / workbook_set.tsv_name
            pairs.append(
                WorkbookPair(
                    workbook_set=workbook_set,
                    model=model,
                    workbook=workbook,
                    tsv=tsv,
                )
            )
    return pairs


def read_tsv(path: Path) -> list[list[str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.reader(handle, delimiter="\t"))


def normalize_grade(value: str) -> int | float:
    if value == "0":
        return 0
    if value == "1":
        return 1
    if value == "0.5":
        return 0.5
    raise ValueError(f"invalid grade {value!r}")


def normalize_for_compare(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def tsv_row_for_compare(row: list[str]) -> list[str]:
    return [row[0], row[1], row[2], row[3]]


def worksheet_row_for_compare(ws: Any, row_number: int) -> list[str]:
    return [normalize_for_compare(ws.cell(row_number, col).value) for col in range(1, 5)]


def find_grading_sheet(workbook: Any, workbook_set: WorkbookSet) -> Any:
    for sheet_name in (workbook_set.grading_sheet, *GRADING_SHEET_CANDIDATES):
        if sheet_name in workbook.sheetnames:
            return workbook[sheet_name]
    raise ValueError(
        f"missing grading sheet for {workbook_set.name}; checked "
        f"{(workbook_set.grading_sheet, *GRADING_SHEET_CANDIDATES)!r}"
    )


def current_table_height(ws: Any) -> int:
    max_row = 0
    for row in range(1, ws.max_row + 1):
        if any(ws.cell(row, col).value not in (None, "") for col in range(1, 5)):
            max_row = row
    return max_row


def count_formula_refs(workbook: Any, needle: str) -> int:
    count = 0
    for ws in workbook.worksheets:
        for row in ws.iter_rows():
            for cell in row:
                value = cell.value
                if isinstance(value, str) and value.startswith("=") and needle in value:
                    count += 1
    return count


def count_stale_formula_refs(workbook: Any) -> int:
    return sum(count_formula_refs(workbook, ref) for ref in STALE_FORMULA_REFS)


def validate_pair(pair: WorkbookPair) -> tuple[list[list[str]], int]:
    if not pair.workbook.exists():
        raise FileNotFoundError(pair.workbook)
    if not pair.tsv.exists():
        raise FileNotFoundError(pair.tsv)

    rows = read_tsv(pair.tsv)
    if not rows:
        raise ValueError(f"{pair.tsv}: empty TSV")
    if rows[0] != HEADER:
        raise ValueError(f"{pair.tsv}: unexpected header {rows[0]!r}")
    bad_widths = sorted({len(row) for row in rows if len(row) != 4})
    if bad_widths:
        raise ValueError(f"{pair.tsv}: expected 4 columns, found widths {bad_widths}")
    bad_grades = sorted({row[2] for row in rows[1:] if row[2] not in VALID_GRADES})
    if bad_grades:
        raise ValueError(f"{pair.tsv}: invalid grades {bad_grades}")

    workbook = load_workbook(pair.workbook)
    try:
        ws = find_grading_sheet(workbook, pair.workbook_set)
        table_height = current_table_height(ws)
        if table_height != len(rows):
            raise ValueError(
                f"{pair.workbook}: TSV rows={len(rows)} but sheet A:D rows={table_height}"
            )
        return rows, count_stale_formula_refs(workbook)
    finally:
        workbook.close()


def apply_pair(pair: WorkbookPair, rows: list[list[str]]) -> None:
    workbook = load_workbook(pair.workbook)
    try:
        ws = find_grading_sheet(workbook, pair.workbook_set)
        if ws.title != pair.workbook_set.grading_sheet:
            ws.title = pair.workbook_set.grading_sheet

        for row_index, row in enumerate(rows, start=1):
            ws.cell(row_index, 1).value = row[0]
            ws.cell(row_index, 2).value = row[1]
            ws.cell(row_index, 3).value = row[2] if row_index == 1 else normalize_grade(row[2])
            ws.cell(row_index, 4).value = row[3]

        for sheet in workbook.worksheets:
            for sheet_row in sheet.iter_rows():
                for cell in sheet_row:
                    value = cell.value
                    if isinstance(value, str) and value.startswith("="):
                        for old_ref in STALE_FORMULA_REFS:
                            value = value.replace(
                                old_ref, f"'{pair.workbook_set.grading_sheet}'!"
                            )
                        cell.value = value

        if METRICS_SHEET in workbook.sheetnames:
            metrics = workbook[METRICS_SHEET]
            metrics["A1"] = GENERATED_BY_LABEL
            metrics["J5"] = pair.workbook_set.grader_label
            metrics["J8"] = GENERATOR_LABEL

        workbook.save(pair.workbook)
    finally:
        workbook.close()


def verify_pair(pair: WorkbookPair, rows: list[list[str]]) -> int:
    workbook = load_workbook(pair.workbook, data_only=False)
    mismatches = 0
    try:
        old_sheets = [
            sheet_name
            for sheet_name in ("Gemini Generation", "Gemini 3.1 Pro Generation")
            if sheet_name in workbook.sheetnames
        ]
        if old_sheets:
            raise ValueError(f"{pair.workbook}: old sheet(s) still exist {old_sheets}")
        if pair.workbook_set.grading_sheet not in workbook.sheetnames:
            raise ValueError(f"{pair.workbook}: new grading sheet missing")

        ws = workbook[pair.workbook_set.grading_sheet]
        if current_table_height(ws) != len(rows):
            raise ValueError(f"{pair.workbook}: table height changed after save")

        for row_index, row in enumerate(rows, start=1):
            actual = worksheet_row_for_compare(ws, row_index)
            expected = tsv_row_for_compare(row)
            if actual != expected:
                print(
                    f"[MISMATCH] {pair.model} row {row_index}: "
                    f"expected={expected!r} actual={actual!r}"
                )
                mismatches += 1

        old_refs = count_stale_formula_refs(workbook)
        if old_refs:
            raise ValueError(f"{pair.workbook}: {old_refs} stale formula refs remain")
        expected_ref_count = count_formula_refs(
            workbook, f"'{pair.workbook_set.grading_sheet}'!"
        )
        if expected_ref_count == 0:
            raise ValueError(
                f"{pair.workbook}: no formulas reference "
                f"{pair.workbook_set.grading_sheet!r}"
            )
        if METRICS_SHEET in workbook.sheetnames:
            metrics = workbook[METRICS_SHEET]
            expected_labels = {
                "A1": GENERATED_BY_LABEL,
                "J5": pair.workbook_set.grader_label,
                "J8": GENERATOR_LABEL,
            }
            for coordinate, expected in expected_labels.items():
                actual = metrics[coordinate].value
                if actual != expected:
                    raise ValueError(
                        f"{pair.workbook}: Metrics!{coordinate} expected "
                        f"{expected!r}, found {actual!r}"
                    )
    finally:
        workbook.close()

    return mismatches


def main() -> int:
    args = parse_args()
    pairs = discover_pairs()
    expected_pair_count = 9 * len(WORKBOOK_SETS)
    if len(pairs) != expected_pair_count:
        print(f"[ERROR] expected {expected_pair_count} workbooks, found {len(pairs)}")
        for pair in pairs:
            print(f"  {pair.workbook_set.name} / {pair.model}: {pair.workbook.relative_to(ROOT)}")
        return 1

    for workbook_set in WORKBOOK_SETS:
        set_pairs = [pair for pair in pairs if pair.workbook_set == workbook_set]
        if len(set_pairs) != 9:
            print(
                f"[ERROR] expected 9 workbooks for {workbook_set.name}, "
                f"found {len(set_pairs)}"
            )
            for pair in set_pairs:
                print(f"  {pair.model}: {pair.workbook.relative_to(ROOT)}")
            return 1

    print("Discovered workbook/TSV pairs:")
    prepared: dict[WorkbookPair, list[list[str]]] = {}
    total_old_refs = 0
    for pair in pairs:
        rows, old_refs = validate_pair(pair)
        prepared[pair] = rows
        total_old_refs += old_refs
        print(
            f"  {pair.workbook_set.name} / {pair.model}: "
            f"rows={len(rows)} stale_formula_refs={old_refs}\n"
            f"    workbook={pair.workbook.relative_to(ROOT)}\n"
            f"    tsv={pair.tsv.relative_to(ROOT)}"
        )

    print(
        f"Preflight passed for {len(pairs)} workbooks; "
        f"stale formula refs={total_old_refs}."
    )
    if not args.apply:
        print("Dry run only. Re-run with --apply to write workbook changes.")
        return 0

    for pair, rows in prepared.items():
        apply_pair(pair, rows)

    mismatch_count = 0
    for pair, rows in prepared.items():
        mismatch_count += verify_pair(pair, rows)

    if mismatch_count:
        print(f"[ERROR] verification found {mismatch_count} TSV/workbook mismatches")
        return 1

    print(f"Updated and verified {len(pairs)} workbooks.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
