#!/usr/bin/env python3
"""Repair Gemini 3.1 Pro Preview auto-grading workbooks.

By default this script performs discovery and verification only. Pass --apply to
write the workbook changes.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from openpyxl import load_workbook


ROOT = Path(__file__).resolve().parents[1]
TSV_NAME = (
    "grading_results__generated-by-gemini-3.1-pro-preview__"
    "graded-by-gemini-3.1-pro-preview.tsv"
)
WORKBOOK_GLOB = (
    "*/Grading/2 stage/6-examples/"
    "*Gemini3.1ProPreviewGeneration_Gemini3.1ProPreviewAutoGrading.xlsx"
)
OLD_SHEET = "Gemini Generation"
NEW_SHEET = "Gemini 3.1 Pro Generation"
OLD_FORMULA_REF = "'GPT-5 Generation'!"
NEW_FORMULA_REF = f"'{NEW_SHEET}'!"
METRICS_SHEET = "Metrics"
METRICS_GENERATED_BY = "Generated by Gemini 3.1 Pro"
METRICS_LLM_NAME = "Gemini 3.1 Pro"
HEADER = ["Type", "Element", "Grading", "Notes"]
VALID_GRADES = {"0", "0.5", "1"}


@dataclass(frozen=True)
class WorkbookPair:
    model: str
    workbook: Path
    tsv: Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Paste Gemini/Gemini grading TSVs into matching xlsx files."
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Write workbook changes. Without this flag, only preflight is run.",
    )
    return parser.parse_args()


def discover_pairs() -> list[WorkbookPair]:
    pairs: list[WorkbookPair] = []
    for workbook in sorted(ROOT.glob(WORKBOOK_GLOB)):
        if workbook.name.startswith("~$"):
            continue
        model = workbook.relative_to(ROOT).parts[0]
        tsv = ROOT / "gemini-generated" / model / TSV_NAME
        pairs.append(WorkbookPair(model=model, workbook=workbook, tsv=tsv))
    return pairs


def read_tsv(path: Path) -> list[list[str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.reader(handle, delimiter="\t"))


def normalize_grade(value: str) -> int | float:
    if value == "0":
        return 0
    if value == "1":
        return 1
    if value == "0.5":
        return 0.5
    raise ValueError(f"invalid grade {value!r}")


def normalize_for_compare(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def tsv_row_for_compare(row: list[str]) -> list[str]:
    return [row[0], row[1], row[2], row[3]]


def worksheet_row_for_compare(ws: Any, row_number: int) -> list[str]:
    return [normalize_for_compare(ws.cell(row_number, col).value) for col in range(1, 5)]


def find_gemini_sheet(workbook: Any) -> Any:
    if NEW_SHEET in workbook.sheetnames:
        return workbook[NEW_SHEET]
    if OLD_SHEET in workbook.sheetnames:
        return workbook[OLD_SHEET]
    raise ValueError(f"missing {OLD_SHEET!r}/{NEW_SHEET!r} sheet")


def current_table_height(ws: Any) -> int:
    max_row = 0
    for row in range(1, ws.max_row + 1):
        if any(ws.cell(row, col).value not in (None, "") for col in range(1, 5)):
            max_row = row
    return max_row


def count_formula_refs(workbook: Any, needle: str) -> int:
    count = 0
    for ws in workbook.worksheets:
        for row in ws.iter_rows():
            for cell in row:
                value = cell.value
                if isinstance(value, str) and value.startswith("=") and needle in value:
                    count += 1
    return count


def validate_pair(pair: WorkbookPair) -> tuple[list[list[str]], int]:
    if not pair.workbook.exists():
        raise FileNotFoundError(pair.workbook)
    if not pair.tsv.exists():
        raise FileNotFoundError(pair.tsv)

    rows = read_tsv(pair.tsv)
    if not rows:
        raise ValueError(f"{pair.tsv}: empty TSV")
    if rows[0] != HEADER:
        raise ValueError(f"{pair.tsv}: unexpected header {rows[0]!r}")
    bad_widths = sorted({len(row) for row in rows if len(row) != 4})
    if bad_widths:
        raise ValueError(f"{pair.tsv}: expected 4 columns, found widths {bad_widths}")
    bad_grades = sorted({row[2] for row in rows[1:] if row[2] not in VALID_GRADES})
    if bad_grades:
        raise ValueError(f"{pair.tsv}: invalid grades {bad_grades}")

    workbook = load_workbook(pair.workbook)
    try:
        ws = find_gemini_sheet(workbook)
        table_height = current_table_height(ws)
        if table_height != len(rows):
            raise ValueError(
                f"{pair.workbook}: TSV rows={len(rows)} but sheet A:D rows={table_height}"
            )
        return rows, count_formula_refs(workbook, OLD_FORMULA_REF)
    finally:
        workbook.close()


def apply_pair(pair: WorkbookPair, rows: list[list[str]]) -> None:
    workbook = load_workbook(pair.workbook)
    try:
        ws = find_gemini_sheet(workbook)
        if ws.title != NEW_SHEET:
            ws.title = NEW_SHEET

        for row_index, row in enumerate(rows, start=1):
            ws.cell(row_index, 1).value = row[0]
            ws.cell(row_index, 2).value = row[1]
            ws.cell(row_index, 3).value = row[2] if row_index == 1 else normalize_grade(row[2])
            ws.cell(row_index, 4).value = row[3]

        for sheet in workbook.worksheets:
            for sheet_row in sheet.iter_rows():
                for cell in sheet_row:
                    value = cell.value
                    if isinstance(value, str) and value.startswith("="):
                        cell.value = value.replace(OLD_FORMULA_REF, NEW_FORMULA_REF)

        if METRICS_SHEET in workbook.sheetnames:
            metrics = workbook[METRICS_SHEET]
            metrics["A1"] = METRICS_GENERATED_BY
            metrics["J5"] = METRICS_LLM_NAME
            metrics["J8"] = METRICS_LLM_NAME

        workbook.save(pair.workbook)
    finally:
        workbook.close()


def verify_pair(pair: WorkbookPair, rows: list[list[str]]) -> int:
    workbook = load_workbook(pair.workbook, data_only=False)
    mismatches = 0
    try:
        if OLD_SHEET in workbook.sheetnames:
            raise ValueError(f"{pair.workbook}: old sheet still exists")
        if NEW_SHEET not in workbook.sheetnames:
            raise ValueError(f"{pair.workbook}: new sheet missing")

        ws = workbook[NEW_SHEET]
        if current_table_height(ws) != len(rows):
            raise ValueError(f"{pair.workbook}: table height changed after save")

        for row_index, row in enumerate(rows, start=1):
            actual = worksheet_row_for_compare(ws, row_index)
            expected = tsv_row_for_compare(row)
            if actual != expected:
                print(
                    f"[MISMATCH] {pair.model} row {row_index}: "
                    f"expected={expected!r} actual={actual!r}"
                )
                mismatches += 1

        old_refs = count_formula_refs(workbook, OLD_FORMULA_REF)
        if old_refs:
            raise ValueError(f"{pair.workbook}: {old_refs} old formula refs remain")
        if METRICS_SHEET in workbook.sheetnames:
            metrics = workbook[METRICS_SHEET]
            expected_labels = {
                "A1": METRICS_GENERATED_BY,
                "J5": METRICS_LLM_NAME,
                "J8": METRICS_LLM_NAME,
            }
            for coordinate, expected in expected_labels.items():
                actual = metrics[coordinate].value
                if actual != expected:
                    raise ValueError(
                        f"{pair.workbook}: Metrics!{coordinate} expected "
                        f"{expected!r}, found {actual!r}"
                    )
    finally:
        workbook.close()

    return mismatches


def main() -> int:
    args = parse_args()
    pairs = discover_pairs()
    if len(pairs) != 9:
        print(f"[ERROR] expected 9 workbooks, found {len(pairs)}")
        for pair in pairs:
            print(f"  {pair.model}: {pair.workbook.relative_to(ROOT)}")
        return 1

    print("Discovered workbook/TSV pairs:")
    prepared: dict[WorkbookPair, list[list[str]]] = {}
    total_old_refs = 0
    for pair in pairs:
        rows, old_refs = validate_pair(pair)
        prepared[pair] = rows
        total_old_refs += old_refs
        print(
            f"  {pair.model}: rows={len(rows)} old_formula_refs={old_refs}\n"
            f"    workbook={pair.workbook.relative_to(ROOT)}\n"
            f"    tsv={pair.tsv.relative_to(ROOT)}"
        )

    print(f"Preflight passed for {len(pairs)} workbooks; old formula refs={total_old_refs}.")
    if not args.apply:
        print("Dry run only. Re-run with --apply to write workbook changes.")
        return 0

    for pair, rows in prepared.items():
        apply_pair(pair, rows)

    mismatch_count = 0
    for pair, rows in prepared.items():
        mismatch_count += verify_pair(pair, rows)

    if mismatch_count:
        print(f"[ERROR] verification found {mismatch_count} TSV/workbook mismatches")
        return 1

    print(f"Updated and verified {len(pairs)} workbooks.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
