#!/usr/bin/env python3
"""Generate RQ3 LaTeX tables from the consolidated experiment CSVs."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "_Figures" / "PaperExperimentData"
OUT_DIR = BASE_DIR / "_Figures" / "PaperTables"

MODEL_ELEMENTS = [
    "Overall Score",
    "State",
    "Transition",
    "Action",
    "Guard",
    "Composite State",
    "History State",
    "Region",
]

GENERATORS = ["Claude4.5Sonnet", "GPT-5.5", "Gemini3.1ProPreview"]
GRADERS = ["Claude4.5Sonnet", "GPT-5.5", "Gemini3.1ProPreview"]

LABELS = {
    "Claude4.5Sonnet": "Claude 4.5 Sonnet",
    "GPT-5.5": "GPT-5.5",
    "Gemini3.1ProPreview": "Gemini 3.1 Pro",
    "Overall Score": "Overall",
    "Composite State": "Composite",
    "History State": "History",
}


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def label(value: str) -> str:
    return LABELS.get(value, value)


def tex(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def pct(value: str | float) -> str:
    return f"{float(value) * 100:.1f}"


def pp(value: str | float) -> str:
    return f"{float(value) * 100:+.1f}"


def write_table(path: Path, caption: str, table_label: str, columns: str, header: str, rows: list[str]) -> None:
    body = "\n".join(rows)
    path.write_text(
        "\n".join(
            [
                "% Generated by _scripts/generate_rq3_latex_tables.py",
                r"\begin{table*}[t]",
                r"\centering",
                r"\small",
                rf"\caption{{{tex(caption)}}}",
                rf"\label{{{table_label}}}",
                rf"\begin{{tabular}}{{{columns}}}",
                r"\toprule",
                header,
                r"\midrule",
                body,
                r"\bottomrule",
                r"\end{tabular}",
                r"\end{table*}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def overall_distribution(rows: list[dict[str, str]], out_dir: Path) -> None:
    by_key = {
        (row["generator"], row["grader"]): row
        for row in rows
        if row["model_element"] == "Overall Score"
    }
    table_rows = []
    for generator in GENERATORS:
        for grader in GRADERS:
            row = by_key[(generator, grader)]
            table_rows.append(
                " & ".join(
                    [
                        tex(label(generator)),
                        tex(label(grader)),
                        row["items"],
                        pct(row["score_0_pct"]),
                        pct(row["score_0_5_pct"]),
                        pct(row["score_1_pct"]),
                    ]
                )
                + r" \\"
            )
    write_table(
        out_dir / "rq3_overall_score_distribution.tex",
        "RQ3 overall LLM-assigned score distribution by generator and grader. Percentages are computed only from LLM grades.",
        "tab:rq3-overall-score-distribution",
        "llrrrr",
        r"Generator & Grader & $n$ & \%0 & \%0.5 & \%1 \\",
        table_rows,
    )


def element_metric_table(
    rows: list[dict[str, str]],
    out_dir: Path,
    metric: str,
    filename: str,
    caption: str,
    table_label: str,
) -> None:
    by_key = {
        (row["generator"], row["grader"], row["model_element"]): row
        for row in rows
        if row["model_element"] in MODEL_ELEMENTS
    }
    table_rows = []
    for grader in GRADERS:
        for element in MODEL_ELEMENTS:
            baseline = by_key[("Claude4.5Sonnet", grader, element)]
            gpt = by_key[("GPT-5.5", grader, element)]
            gemini = by_key[("Gemini3.1ProPreview", grader, element)]
            baseline_value = float(baseline[metric])
            gpt_value = float(gpt[metric])
            gemini_value = float(gemini[metric])
            table_rows.append(
                " & ".join(
                    [
                        tex(label(grader)),
                        tex(label(element)),
                        pct(baseline_value),
                        pct(gpt_value),
                        pp(gpt_value - baseline_value),
                        pct(gemini_value),
                        pp(gemini_value - baseline_value),
                    ]
                )
                + r" \\"
            )
    write_table(
        out_dir / filename,
        caption,
        table_label,
        "llrrrrr",
        r"Grader & Element & Claude gen. & GPT gen. & $\Delta$ GPT & Gemini gen. & $\Delta$ Gemini \\",
        table_rows,
    )


def cross_grader_rankings(rows: list[dict[str, str]], out_dir: Path) -> None:
    by_key: dict[tuple[str, str], list[dict[str, str]]] = {}
    for row in rows:
        if row["model_element"] not in MODEL_ELEMENTS:
            continue
        by_key.setdefault((row["generator"], row["model_element"]), []).append(row)

    table_rows = []
    for generator in GENERATORS:
        for element in MODEL_ELEMENTS:
            ranked = sorted(
                by_key[(generator, element)],
                key=lambda row: (int(row["rank_by_score_1"]), row["grader"]),
            )
            cells = []
            for row in ranked:
                cells.append(f"{tex(label(row['grader']))} ({pct(row['score_1_pct'])})")
            table_rows.append(
                " & ".join([tex(label(generator)), tex(label(element)), *cells]) + r" \\"
            )
    write_table(
        out_dir / "rq3_cross_grader_score1_rankings.tex",
        "RQ3 cross-grader ordering by score-1 rate for each generator and model element. Equal percentages indicate ties.",
        "tab:rq3-cross-grader-score1-rankings",
        "lllll",
        r"Generator & Element & Highest \%1 & Middle \%1 & Lowest \%1 \\",
        table_rows,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=Path, default=DATA_DIR)
    parser.add_argument("--out-dir", type=Path, default=OUT_DIR)
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    score_rows = read_csv(args.data_dir / "rq3_grading_score_distribution.csv")
    ranking_rows = read_csv(args.data_dir / "rq3_cross_grader_rankings.csv")

    overall_distribution(score_rows, args.out_dir)
    element_metric_table(
        score_rows,
        args.out_dir,
        "score_1_pct",
        "rq3_element_score1_rates.tex",
        "RQ3 model-element score-1 rates by grader. Claude-generated state machines are the baseline; deltas compare GPT- and Gemini-generated inputs against that baseline.",
        "tab:rq3-element-score1-rates",
    )
    element_metric_table(
        score_rows,
        args.out_dir,
        "score_0_5_pct",
        "rq3_element_partial_credit_rates.tex",
        "RQ3 model-element partial-credit rates by grader. Claude-generated state machines are the baseline; deltas compare GPT- and Gemini-generated inputs against that baseline.",
        "tab:rq3-element-partial-credit-rates",
    )
    cross_grader_rankings(ranking_rows, args.out_dir)

    print(f"Wrote RQ3 LaTeX tables to {args.out_dir}")


if __name__ == "__main__":
    main()
